### PR TITLE
Tested with Django 2.1

### PR DESCRIPTION
**Pull request by maerteijn**
Also:
-  added Python 3.4, 3.5 and 3.7, removed unsupported Django versions
- Reconfigured the travis matrix to be more explicit what it's doing.
- Also converted the README.md to README.rst so pypi will parse it more nicely.

Speaking of pypi, I noticed that version 1.1.14 and 1.1.15 are not released, is that for a specific reason?

### CODE REVIEW

**Comment by philippeowagner** [comment]
Nice! I will have a look on Friday.

**Comment by lorddaedra** [comment]
@maerteijn 

1.  I suggest to test Django 2.1 with Python 3.7 (better save 3.6 too and add new line with 3.7). 
- py36-django21
- py37-django21

2. Also looks as good idea remove old outdated Django versions: 1.8, 1.9, 1.10. Based on information from page https://www.djangoproject.com/download/ they are outdated, will never get updates and should not be used for security reasons...

3. Also Python 3.4 and 3.5 is still supported https://www.python.org/dev/peps/pep-0429/#id4
So it looks as good idea add them too for Django versions, which has official support for them...

- py34-django111
- py34-django20
- py35-django111
- py35-django20
- py35-django21

**Comment by philippeowagner** [comment]
@maerteijn could you please re-add 1.8 (LTS). Thank you.

**Comment by maerteijn** [comment]
@philippeowagner I readded Django 1.8 again. Now there is an impressive build matric 😄 

https://travis-ci.org/arteria/django-background-tasks/builds/434961809

PS, Django 1.8 is a LTS release but as lorddaedra mentioned the LTS support is already expired (stopped in april this year). Something we should mention in the docs / readme?

**Comment by lorddaedra** [comment]
Based on PEP 10 [https://www.python.org/dev/peps/pep-0010/ ] I can measure my opinion about supporting outdated software as "-0" or "-1". It's usually bad idea in most cases for public projects. "-0" for this case... 

To be honestly, it's acceptable [as technical debt 💩] for some sort of private projects.

But it's just my opinion, of course. The main contributors of that package should decide this... I'm going to use it with Python 3.7 & Django 2.1 for now so I'll be happy to see 1.2 release anyway with or w/o 1.8 support...

> Something we should mention in the docs / readme?

Something about technical debt may be? I always suggest to follow official `Supported versions` section on page https://www.djangoproject.com/download/#supported-versions

And also I suggest create file with changelog data.

**Comment by maerteijn** [comment]
I added a note about  Django 1.8. Versioning and release notes is something the maintainer should do.

@philippeowagner Is this pull request acceptable now as it  is?

**Comment by philippeowagner** [comment]
@maerteijn thanks!

**Comment by philippeowagner** [comment]
https://pypi.org/project/django-background-tasks/1.2.0/

**Pull request merged**
